defaultLocale: en
localizedSettings:
  displayName: Detective Frankie
  pronunciation: Detective Frankie
  themeCustomization:
    backgroundColor: '#FAFAFA'
    imageCornerStyle: CURVED
    primaryColor: '#101010'
  voice: male_1
projectId: detective-frankie
